//Gfx converted using Mollusk's PAGfxConverter

//This file contains all the .c, for easier inclusion in a project


// Background files : 
#include "tilegfx0.c"
#include "tilegfx1.c"
#include "tilegfx2.c"
#include "tilegfx3.c"
#include "tilegfx4.c"
#include "bg_back_0.c"
#include "bg_back_1.c"
#include "bg_back_2.c"
#include "bg_hills_0.c"
#include "bg_hills_1.c"
#include "bg_hills_2.c"
#include "level_1.c"
#include "level_2.c"
#include "level_3.c"
#include "level_4.c"
#include "level_5.c"
#include "level_6.c"
#include "level_7.c"
#include "level_8.c"
#include "level_9.c"
#include "level_10.c"
#include "level_11.c"
#include "level_12.c"
#include "level_13.c"
#include "level_14.c"
#include "level_15.c"
#include "level_16.c"
#include "level_17.c"
#include "level_18.c"
#include "level_19.c"
#include "level_20.c"
#include "level_21.c"
#include "level_22.c"
#include "level_23.c"
#include "level_24.c"
#include "level_25.c"
#include "level_26.c"
#include "level_27.c"
#include "level_28.c"
#include "level_29.c"
#include "level_30.c"
#include "level_31.c"
#include "level_32.c"
#include "level_33.c"
#include "level_34.c"
#include "level_35.c"
#include "level_36.c"
#include "level_37.c"
#include "level_38.c"
#include "level_39.c"
#include "level_40.c"
#include "level_41.c"
#include "info.c"

// Palette files : 
#include "tilegfx0.pal.c"
#include "tilegfx1.pal.c"
#include "tilegfx2.pal.c"
#include "tilegfx3.pal.c"
#include "tilegfx4.pal.c"
#include "bg_back_0.pal.c"
#include "bg_back_1.pal.c"
#include "bg_back_2.pal.c"
#include "bg_hills_0.pal.c"
#include "bg_hills_1.pal.c"
#include "bg_hills_2.pal.c"
#include "info.pal.c"
