//Gfx converted using Mollusk's PAGfxConverter

//This file contains all the .c, for easier inclusion in a project


// Sprite files : 
#include "player.c"
#include "player_head.c"
#include "player_arm.c"
#include "superplayer.c"
#include "effects.c"
#include "effect_explosion1.c"
#include "effect_humo.c"
#include "effect_raise.c"
#include "effect_ballraise.c"
#include "items.c"
#include "autorun.c"
#include "coin.c"
#include "pause_select.c"
#include "pause_text.c"
#include "status_weapon.c"
#include "status_weapon_1.c"
#include "status_weapon_2.c"
#include "weapon_1.c"
#include "weapon_2.c"
#include "weapon_3.c"
#include "weapon_4.c"
#include "weapon_5.c"
#include "weapon_6.c"
#include "weapon_7.c"
#include "weapon_8.c"
#include "weapon_9.c"
#include "monster_0.c"
#include "monster_1.c"
#include "monster_2.c"
#include "monster_3.c"
#include "monster_4.c"
#include "monster_5.c"
#include "monster_6.c"
#include "monster_7.c"
#include "monster_8.c"
#include "boss_0.c"
#include "boss_1.c"
#include "boss_2.c"
#include "boss_3.c"

// Palette files : 
#include "player.pal.c"
#include "superplayer.pal.c"
#include "effects.pal.c"
#include "itempal.pal.c"
#include "weaponstatus.pal.c"
#include "weapon.pal.c"
#include "monster.pal.c"
