//Gfx converted using Mollusk's PAGfxConverter

//This file contains all the .c, for easier inclusion in a project


// Sprite files : 
#include "text.c"
#include "title_text.c"
#include "hp_bar.c"
#include "ammo_bar.c"
#include "arrow.c"
#include "lvlthumb.c"
#include "lvlsel.c"
#include "slotempty.c"
#include "savebutton.c"
#include "backbutton.c"
#include "shopbutton.c"
#include "buybutton.c"
#include "exitbutton.c"
#include "selectbutton.c"
#include "selectlevelbutton.c"
#include "selectsavebutton.c"
#include "mode_easy.c"
#include "mode_normal.c"
#include "mode_hard.c"
#include "shop_select.c"
#include "map.c"
#include "map_pointer.c"

// Background files : 
#include "title_bg1.c"
#include "title_bg2.c"
#include "title_bg3.c"
#include "game_shop.c"
#include "game_shop_bottom.c"
#include "menu_bg.c"
#include "menu_bgd.c"
#include "menu_extras.c"
#include "menu_bggame.c"
#include "game_selectsave.c"

// Palette files : 
#include "text.pal.c"
#include "title_text.pal.c"
#include "hp_bar.pal.c"
#include "ammo_bar.pal.c"
#include "arrow.pal.c"
#include "lvl.pal.c"
#include "slotempty.pal.c"
#include "buttons.pal.c"
#include "shop_select.pal.c"
#include "map.pal.c"
#include "map_pointer.pal.c"
#include "title_bg1.pal.c"
#include "title_bg2.pal.c"
#include "title_bg3.pal.c"
#include "game_shop.pal.c"
#include "game_shop_bottom.pal.c"
#include "menu_bg.pal.c"
#include "menu_bgd.pal.c"
#include "menu_extras.pal.c"
#include "menu_bggame.pal.c"
#include "game_selectsave.pal.c"
